Fix an SBT compilation error:
scalameta/build.sbt:208: error: type mismatch;
 found   : String("\033]50;ClearScrollback\07")
 required: sbt.TaskKey[String]
  print("\u001b]50;ClearScrollback\u0007")
        ^
sbt.compiler.EvalException: Type error in expression
	at sbt.compiler.Eval.checkError(Eval.scala:384)

Make cls work for Apple Terminal & xterm.